### ISSUE TITLE
strAPI not running locally

### ISSUE THREAD

**Issue by ryleyw** [bcgov/digital.gov.bc.ca#190]
`docker-compose up` does not successfully start strAPi locally

docker logs strapi show the following error:

`error TypeError: Cannot read property 'defaultConnection' of undefined
    at module.exports (/srv/app/node_modules/strapi/lib/core/bootstrap.js:35:71)
    at Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:317:11)
    at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:190:7)`

This showed up after we got strapi running in the pipeline.

**Comment by ryleyw** [comment]
remember to npm install

**Comment by ryleyw** [comment]
error Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.

Need someone to see if this works on their machine, possibly a strapi install error on macs, could just be my machine

**Comment by ryleyw** [comment]
Solution is to delete node_modules while strapi is running, forcing the docker console to compensate and run yarn install
